[build]
target = "index.html"
dist = "dist"
features = "web"

[watch]
watch = ["src", "index.html", "style"]

[serve]
port = 8080
open = false

[[hooks]]
stage = "pre_build"
command = "cp"
command_arguments = ["robots.txt", "dist/"]
