name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('.github/workflows/**.yaml') }}

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('.github/workflows/**.yaml') }}

      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('.github/workflows/**.yaml') }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  pre-publish-crates:
    name: Pre publish Checks for Crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.rustup
            ~/.cargo
            target
          key: ${{ runner.os }}-rust-${{ hashFiles('.github/workflows/**.yaml') }}

      - name: Verify Package
        uses: actions-rs/cargo@v1
        with:
          command: package
          args: --workspace

      # TODO: Find way to fail when version already exists on crates.io
      - name: Dry run publish for core crate
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
